export const Project = [
  {
    id: 1,
    title: "Website Ngamplop",
    desc: "Website untuk mencatat pengeluaran keuangan pas waktu kondangan",
    stack: ["Laravel", "Tailwind", "Javascript", "AlpineJS"],
    gambar: "./project/ngamplop.png",
    github: "https://github.com/budayyy/ngamplop",
    link: "http://34.101.212.87/",
  },
  {
    id: 2,
    title: "Website CV Online Budi Setiawan",
    desc: "Website untuk mengetahui CV sendiri secara online",
    stack: ["React JS", "Tailwind", "Javascript"],
    gambar: "./project/cv-budi-setiawan.png",
    github: "https://github.com/budayyy/cv-budi-setiawan",
    link: "https://budayyy.github.io/cv-budi-setiawan/",
  },
  {
    id: 3,
    title: "Sistem Pendukung Keputusan Penyesuaian Lahan Untuk Tanaman",
    desc: "sistem pendukung keputusan penyesuaian lahan untuk tanaman pangan ini bertujuan agar data dari kriteria - kriteria lahan kemudian data tersebut dicocokan dengan data uji dan yang dihasilkan berupa rekomendasi tanaman yang untuk ditanam. pencocokan pada sistem ini menggunakan metode profile matching.",
    stack: ["PHP", "JavaScript", "Bootstrap", "HTML", "CSS"],
    gambar: "./project/spk-lahan.png",
    github: "https://github.com/budayyy",
    link: "https://spk-lahan-pm.000webhostapp.com/",
  },
  {
    id: 4,
    title: "Website Administrator Jannahku",
    desc: "Website dari admin jannahku yang dibuat dengan menggunakan framework laravel. jannahku sendiri merupakan aplikasi dating apps islami.",
    stack: ["Laravel", "JavaScript", "Bootstrap"],
    gambar: "./project/admin-jannahku.png",
    github: "https://github.com/budayyy",
    link: "https://admin.jannahku.com/",
  },
  {
    id: 5,
    title: "Website Administrator Bina Apps",
    desc: "Website dari admin bina apps yang dibuat dengan menggunakan framework laravel. Bina Apps sendiri merupakan aplikasi jual beli bahan bangunan dan jasa tukang.",
    stack: ["Laravel", "JavaScript", "Bootstrap"],
    gambar: "./project/admin-jannahku.png",
    github: "https://github.com/budayyy",
    link: "https://admin.bina-apps.com/",
  },
  {
    id: 6,
    title: "Website Undangan by jannahku",
    desc: "Website dari undangan by jannahku yang dibuat dengan menggunakan framework laravel. undangan by jannahku sendiri merupakan website penyedia layanan undangan pernikahan digital.",
    stack: ["Laravel", "JavaScript", "Bootstrap"],
    gambar: "./project/undangan-jannahku.png",
    github: "https://github.com/budayyy",
    link: "https://undangan.jannahku.com/",
  },
  {
    id: 7,
    title: "Website Landing Page GMJ Global Energy",
    desc: "Website dari GMJ Global Energy yang dibuat dengan menggunakan framework laravel dengan TailwindCSS. GMJ GLobal Energy sendiri merupakan perusahaan konsultan dan jasa dibidang minyak dan gas.",
    stack: ["Laravel", "JavaScript", "Bootstrap"],
    gambar: "./project/gmj.png",
    github: "https://github.com/budayyy",
    link: "https://www.gmjglobalenergy.com/",
  },
  {
    id: 8,
    title: "Website Landing Page BAQI Apps",
    desc: "Website dari Aplikasi BAQI Apps yang dibuat dengan menggunakan framework laravel dengan TailwindCSS. BAQI Apps sendiri merupakan aplikasi baca quran interaktif.",
    stack: ["Laravel", "JavaScript", "Bootstrap"],
    gambar: "./project/baqi.png",
    github: "https://github.com/budayyy",
    link: "https://baqi-app.jannahku.com/",
  },
  {
    id: 9,
    title: "Website Landing Page Bina Apps",
    desc: "Website dari Aplikasi Bina Apps yang dibuat dengan menggunakan framework laravel dengan TailwindCSS. Bina Apps sendiri merupakan aplikasi jual beli bahan bangunan dan jasa tukang.",
    stack: ["Laravel", "JavaScript", "Bootstrap"],
    gambar: "./project/bina.png",
    github: "https://github.com/budayyy",
    link: "https://www.bina-apps.com/",
  },
  {
    id: 10,
    title: "Kedai Warung Kopi",
    desc: "Website sederhana menggunakan html, css dan javascript yang menjelaskan tentang landing page kedai warung kopi sederhana",
    stack: ["HTML", "JavaScript", "CSS"],
    gambar: "./project/kedai-warung-kopi.png",
    github: "https://github.com/budayyy/warung-kopi",
    link: "https://www.bina-apps.com/",
  },
];
